#:schema node_modules/wrangler/config-schema.json
name = "fuiz"
compatibility_date = "2026-01-27"
main = ".svelte-kit/cloudflare/_worker.js"
assets = { directory = ".svelte-kit/cloudflare", binding = "ASSETS" }
compatibility_flags = ["nodejs_compat", "nodejs_als"]

services = [{ binding = "COUNTER", service = "counter" }]

[vars]
BUN_VERSION = "1.3.5"
GIT_PROVIDER = "gitlab"
GIT_REPO_OWNER = "fuiz"
GIT_REPO_NAME = "library"
GIT_DEFAULT_BRANCH = "main"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DATABASE"
database_name = "fuiz"
database_id = "51b4dee7-59e7-42d9-9b90-9be2d4e6500e"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "fuiz"

[[kv_namespaces]]
binding = "MAP"
id = "c8aca143fe384d89aa82e431cf579069"

[[kv_namespaces]]
binding = "PUBLISH_JOBS"
id = "6f60c7ca01bb45ba84f5ccb5c16eb4b6"
